-- Paramètres document (TVA, remise, timbre) sur devis et factures.
-- Colonnes présentes dans schema.prisma mais jamais migrées.

ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "applyVat" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "applyFiscalStamp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "fiscalStamp" DECIMAL(14,3) NOT NULL DEFAULT 1.000;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "discountEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "discountRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "showCurrencyOnLines" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "applyVat" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "applyFiscalStamp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "fiscalStamp" DECIMAL(14,3) NOT NULL DEFAULT 1.000;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "discountEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "discountRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "showCurrencyOnLines" BOOLEAN NOT NULL DEFAULT true;
